// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2ak440-nxZgmucGBdE6IVEVJxbmSZGUE',
    appId: '1:222708256869:web:3c0cb59e4e8f530b6fb68c',
    messagingSenderId: '222708256869',
    projectId: 'face-attendance-system-e1b3b',
    authDomain: 'face-attendance-system-e1b3b.firebaseapp.com',
    storageBucket: 'face-attendance-system-e1b3b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD860rJqlZCm9p_TpNaGkgBwDSaEZCQpU4',
    appId: '1:222708256869:android:6712ae2df7b90af06fb68c',
    messagingSenderId: '222708256869',
    projectId: 'face-attendance-system-e1b3b',
    storageBucket: 'face-attendance-system-e1b3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYM_J53eTB1kbv5M0jmgYt7f4-O2oOsVc',
    appId: '1:222708256869:ios:99c97123e79e39c46fb68c',
    messagingSenderId: '222708256869',
    projectId: 'face-attendance-system-e1b3b',
    storageBucket: 'face-attendance-system-e1b3b.firebasestorage.app',
    iosBundleId: 'com.madjanjua.faceAttendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYM_J53eTB1kbv5M0jmgYt7f4-O2oOsVc',
    appId: '1:222708256869:ios:99c97123e79e39c46fb68c',
    messagingSenderId: '222708256869',
    projectId: 'face-attendance-system-e1b3b',
    storageBucket: 'face-attendance-system-e1b3b.firebasestorage.app',
    iosBundleId: 'com.madjanjua.faceAttendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2ak440-nxZgmucGBdE6IVEVJxbmSZGUE',
    appId: '1:222708256869:web:80a4dc018d5394c56fb68c',
    messagingSenderId: '222708256869',
    projectId: 'face-attendance-system-e1b3b',
    authDomain: 'face-attendance-system-e1b3b.firebaseapp.com',
    storageBucket: 'face-attendance-system-e1b3b.firebasestorage.app',
  );
}
